keys:

  - &user:
    - &dev-shell age1t5eu9lzw5pqec8mu3vh27e55fce37h8ec2sd0nplqf8xukchnc9sz6adz2

  - &platform:
    - &swtpm age1tpm1qf8hp3zgj7k8f7e8562aswmul0mvscdvpugyafqvw3chgkn799yywqw33w8

creation_rules:

  - key_groups:
    - age:
      - *swtpm
      - *dev-shell

stores:

  json:
    indent: 2

  json_binary:
    indent: 2

  yaml:
    indent: 2
